# In the name of Allah, the most beneficent, the most merciful...
import smtplib
import random
import datetime as dt

my_email = "riza.khan1662002@gmail.com"
password = "mcfecbqjrvagylix"
# # message = "Subject: Allahu Akbar\n\n" \
# #           "In the name of Allah the most beneficent the most merciful..\n Subhan allahi wa bihamdihi subhan allahil " \
# #           "azeem\nThis is a test mail generated by my python code. "
#
# with smtplib.SMTP("smtp.gmail.com") as connection: connection.starttls() connection.login(user=my_email,
# password=password) connection.sendmail(from_addr=my_email, to_addrs="riza.mansuri11@gmail.com", msg="Subject:
# Hello\n\nThis is the body of mail.")

now = dt.datetime.now()
current_day = now.weekday()
#print(current_day)
if current_day==6:
    with open("quotes.txt", "r") as quotes:
        all_quotes = quotes.readlines()
        message = random.choice(all_quotes)
    with smtplib.SMTP("smtp.gmail.com") as connection:
        connection.starttls()
        connection.login(user=my_email, password=password)
        connection.sendmail(from_addr=my_email,
                            to_addrs="riza.mansuri11@gmail.com",
                            msg=f"Subject: Today's Quote from Riza's Python Project\n\n{message}")


